version: '1'
services:
  db:
    build:
      context: ./MySQL
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_rest
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    container_name: golang_db
    ports:
        - "3306:3306"
    tty: true
  app:
      build:
        context: ./Go
      volumes:
        - "./Go:/go"
      container_name: golang_app
      ports:
        - "5000:5000"
      tty: true
      depends_on:
        - db
